version: 2.1
jobs:
  build:
    docker:
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip instal -r requirements.txt
      - run:
          name: Run tests
          command: coverage run -m unittest && coverage xml && coverage report -m
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy
          command: npm run deploy
